### ISSUE TITLE
Warnings are treated as errors. 

### ISSUE THREAD

**Issue by MoMannn** [specron/framework#12]
When compiling solidity code if there are compiler warnings there are treated and shown as errors.

Example:

<img width="1057" alt="screen shot 2018-08-23 at 08 35 58" src="https://user-images.githubusercontent.com/8865298/44508873-24673a80-a6b0-11e8-83f9-e34e34b111ea.png">

**Comment by xpepermint** [comment]
Yeah, it's hard to tell what's a warning and what's an error.

**Comment by MoMannn** [comment]
#24
