### ISSUE TITLE
Sample contract

### ISSUE THREAD

**Issue by fulldecent** [specron/framework#46]
Can someone please run

$ mkdir myProject
$ cd myProject
Initialize the project and install the dependencies.

$ specron init
$ npm install
Run tests to verify everything works as expected.

$ npm test

and then save that to specron/hello-world

Also add Travis integration.

This will help me quickly see if specron is right for me.

---

I have already complained to Truffle about the magic and boilerplates required there so specron could be a fresh relief!

https://github.com/trufflesuite/truffle/issues/1382

**Comment by xpepermint** [comment]
Don't forget the installation step as described in the documentation:

```
$ npm install -g @specron/cli web3@1.0.0-beta.36 solc
```

Here's the repository to the initialized project folder with Travis integration:
- https://github.com/xpepermint/specron-example
- https://travis-ci.org/xpepermint/specron-example

**Comment by xpepermint** [comment]
@fulldecent is this what you requested?

**Comment by fulldecent** [comment]
Thank you! Looks great. Added link here https://github.com/specron/framework/pull/53

**Comment by xpepermint** [comment]
Thanks.
