### ISSUE TITLE
Add flatten functionality

### ISSUE THREAD

**Issue by MoMannn** [specron/framework#48]
It would be cool to have a `specron flatten` command that would flatten all the smart contracts and dependencies into one file.

**Comment by fulldecent** [comment]
Flattening is usually done very poorly in the wild. Maybe we can do this a lot better than everybody else with a couple conventions.

* Allow (and encourage) developer to specify source file ordering
  * specron flatten fileA.sol fileB.sol fileC.sol
    * Produces errors if a dependency of A, B, or C is not specified on the command line
  * specron flatten --use-include-order fileC.sol
    * Works like you'd expect
  * specron flatten fileC.sol
    * This is an error, we don't want people to run it this way. It means they didn't consider the readability of the resulting file.
* Allow (and encourage) developer to include a header at the top of the file
* Allow (and encourage) developer to use these features as part of a build script (see how Su Squares does it at https://github.com/su-squares/ethereum-contract/blob/master/test/confirm-sol-merged.sh)

**Comment by xpepermint** [comment]
https://github.com/specron/framework/pull/66
